// Set top and bottom color to white
Window.SetBackgroundTopColor (1,1,1,);
Window.SetBackgroundBottomColor (1,1,1);


// Screen size
screen.w = Window.GetWidth();
screen.h = Window.GetHeight();
screen.half.w = Window.GetWidth() / 2;
screen.half.h = Window.GetHeight() / 2;

// Question prompt
question = null;
answer = null;

// Message
message = null;

// Password prompt
bullets = null;
prompt = null;
bullet.image = Image.Text("*", 1, 1, 1);

// Flow
state.status = "play";
state.time = 0.0;

//--------------------------------- Display Resolution --------------------------

bootprogressmsg.sprite = Sprite();
progress.image = Image.Text("Regenerate with this resolution:\n\n"+screen.h, 1, 0, 0, 1, "droidsansmono 72", "left");
bootprogressmsg.sprite.SetImage(progress.image);
bootprogressmsg.sprite.SetX(400);
bootprogressmsg.sprite.SetY(600);
bootprogressmsg.sprite.SetOpacity(1.0);




//-------------------------------- Password prompt -------------------------------
fun DisplayQuestionCallback(prompt, entry) {
  question = null;
  answer = null;

  if (entry == "")
      entry = "<answer>";

  question.image = Image.Text(prompt, 1, 0, 0);
  question.sprite = Sprite(question.image);
  question.sprite.SetX(screen.half.w - question.image.GetWidth() / 2);
  question.sprite.SetY(screen.h - 4 * question.image.GetHeight());

  answer.image = Image.Text(entry, 0, 0, 0);
  answer.sprite = Sprite(answer.image);
  answer.sprite.SetX(screen.half.w - answer.image.GetWidth() / 2);
  answer.sprite.SetY(screen.h - 2 * answer.image.GetHeight());
}
Plymouth.SetDisplayQuestionFunction(DisplayQuestionCallback);


//-------------------------------- Password prompt -------------------------------
fun DisplayPasswordCallback(nil, bulletCount) {
  state.status = "pause";
  totalWidth = bulletCount * bullet.image.GetWidth();
  startPos = screen.half.w - totalWidth / 2;

  prompt.image = Image.Text("Enter Password", 0, 0, 0);
  prompt.sprite = Sprite(prompt.image);
  prompt.sprite.SetX(screen.half.w - prompt.image.GetWidth() / 2);
  prompt.sprite.SetY(screen.h - 4 * prompt.image.GetHeight());

  // Clear all bullets (user might hit backspace)
  bullets = null;
  for (i = 0; i < bulletCount; i++) {
      bullets[i].sprite = Sprite(bullet.image);
      bullets[i].sprite.SetX(startPos + i * bullet.image.GetWidth());
      bullets[i].sprite.SetY(screen.h - 2 * bullet.image.GetHeight());
  }
}
Plymouth.SetDisplayPasswordFunction(DisplayPasswordCallback);


//------------------------- Normal display (unset all text) ----------------------
fun DisplayNormalCallback() {
    state.status = "play";
    bullets = null;
    prompt = null;
    message = null;
    question = null;
    answer = null;
}
Plymouth.SetDisplayNormalFunction(DisplayNormalCallback);


//---------------------------------- Message --------------------------------
fun MessageCallback(text) {
    message.image = Image.Text(text, 1, 0, 0);
    message.sprite = Sprite(message.image);
    message.sprite.SetPosition(screen.half.w - message.image.GetWidth() / 2, message.image.GetHeight());
}
Plymouth.SetMessageFunction(MessageCallback);
